[repository]
name = "sc-volto-light-theme"
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "semver"
container_images_prefix = "ghcr.io/simplesconsultoria/sc-volto-light-theme"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "sc.voltolighttheme"
path = "backend"
code_path = "src/sc/voltolighttheme"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = true

[frontend.package]
name = "@simplesconsultoria/volto-light-theme"
path = "frontend/packages/volto-light-theme"
code_path = "src"
changelog = "frontend/packages/volto-light-theme/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-light-theme/towncrier.toml"
base_package = "@plone/volto"
publish = true

[cookieplone]
template = "monorepo_addon"
template_version = "66a74c3744f84b177401b25836d3702c2ef1b5f3"
generated_date = "2026-07-08 16:47:22"
